name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-windows:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - run: cargo build --profile release-opt
      - run: cargo clippy
      - run: cargo test
      - uses: actions/upload-artifact@v4
        with:
          name: hash-gui-win
          path: target/release-opt/hash-gui.exe
          if-no-files-found: error
  build:
    strategy:
      max-parallel: 2
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get OS name
        id: os-name
        run: echo "OS_NAME=$(echo ${{ matrix.os }} | sed 's/-latest//')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - run: cargo build --profile release-opt
      - run: cargo clippy
      - run: cargo test
      - uses: actions/upload-artifact@v4
        with:
          name: hash-gui-${{ steps.os-name.outputs.OS_NAME }}
          path: target/release-opt/hash-gui
          if-no-files-found: error
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo run fmt
